# Generated by Django 2.2.7 on 2019-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_pizza', '0002_loaddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='comment',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.CharField(choices=[('XL', 'Large'), ('MD', 'Medium'), ('SM', 'Small')], max_length=2),
        ),
    ]
