# Generated by Django 2.2.8 on 2020-02-01 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testing_pizza', '0003_auto_20191124_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='pizzaingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='pizzamenuitem',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='pizzaorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='pizzasize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterField(
            model_name='address',
            name='full',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pizzaingredient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='pizzamenuitem',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='testing_pizza.PizzaIngredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='pizzamenuitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='comment',
            field=models.CharField(blank=True, max_length=140, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='date_delivered',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='+/-'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='testing_pizza.Address', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='exclude',
            field=models.ManyToManyField(blank=True, to='testing_pizza.PizzaIngredient', verbose_name='Исключенные'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='extra',
            field=models.ManyToManyField(blank=True, related_name='pizzas_extras', to='testing_pizza.PizzaIngredient', verbose_name='Доп.'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='testing_pizza.PizzaMenuItem', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='testing_pizza.PizzaSize', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.CharField(choices=[('XL', 'Большая'), ('MD', 'Средняя'), ('SM', 'Маленькая')], max_length=2, verbose_name='Размер'),
        ),
    ]
